make cli GEN_TRANS_TYPE=i2cmb_test
make run_cli GEN_TRANS_TYPE=test_i2cmb_consecutive_starts
make run_cli GEN_TRANS_TYPE=test_i2cmb_consecutive_stops
make run_cli GEN_TRANS_TYPE=test_i2cmb_reg_addr
make run_cli GEN_TRANS_TYPE=test_i2cmb_reg_vals
make run_cli GEN_TRANS_TYPE=test_i2cmb_rw_ability
make run_cli GEN_TRANS_TYPE=test_i2cmb_busses
make run_cli GEN_TRANS_TYPE=test_i2cmb_directed
make run_cli GEN_TRANS_TYPE=test_i2cmb_randomized
make merge_coverage
make view_coverage